spring.application.name=pipefyApi
server.port=8080

# CREDENCIAIS (carregadas do .env)
pipefy.api-url=${PIPEfy_API_URL}
pipefy.token=${PIPEfy_TOKEN}
pipefy.fase-fim-id=${PIPEfy_FASE_FIM_ID}


# HABILITAR CORES NOS LOGS
spring.output.ansi.enabled=ALWAYS

# N�VEIS DE LOG
logging.level.root=INFO
logging.level.com.profectum.pipefy=INFO

# PADR�O DE LOG COLORIDO (igual Spring Boot padr�o)
logging.pattern.console=%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx